/* acconf.h.  Generated by configure.  */
/* acconf.h.in.  Generated from configure.in by autoheader.  */

/* dirent uses d_namlen */
#define DIRENT_HAS_D_NAMLEN 

/* Define to 1 if you have the `access' function. */
#define HAVE_ACCESS 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `getpwnam' function. */
#define HAVE_GETPWNAM 1

/* Define to 1 if you have the `getpwuid' function. */
#define HAVE_GETPWUID 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mktime' function. */
#define HAVE_MKTIME 1

/* Define to 1 if you have the `realpath' function. */
#define HAVE_REALPATH 1

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strptime' function. */
#define HAVE_STRPTIME 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if the system has the type `_Bool'. */
#define HAVE__BOOL 1

/* Name of package */
#define PACKAGE "attic"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "johnw@newartisans.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "attic"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "attic 1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "attic"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0"

/* st_atim */
/* #undef STAT_USES_ST_ATIM */

/* st_atime */
/* #undef STAT_USES_ST_ATIME */

/* st_atimensec */
/* #undef STAT_USES_ST_ATIMENSEC */

/* st_atimespec */
#define STAT_USES_ST_ATIMESPEC 

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Version number of package */
#define VERSION "1.0"

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */
