#!/bin/sh

touch AUTHORS COPYING

if which glibtoolize > /dev/null 2>&1; then
    glibtoolize --automake -f -c
else
    libtoolize --automake -f -c
fi
aclocal
autoheader
if [ "$1" = "--dist" ]; then
    shift 1
    automake -a -c -f -i
else
    automake -a -c -f
fi
autoconf

INCDIRS="-I/sw/include -I/usr/local/include"
INCDIRS="$INCDIRS -Wno-long-double"

LIBDIRS="-L/sw/lib -L/usr/local/lib"

SWITCHES="--disable-shared"

if [ "$1" = "--debug" ]; then
    shift 1
    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" CXXFLAGS="-g" $SWITCHES
else
    ./configure CPPFLAGS="$INCDIRS" LDFLAGS="$LIBDIRS" $SWITCHES
fi

rm AUTHORS COPYING
